[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = ["@openzeppelin/=node_modules/@openzeppelin/"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
