"use client";

import { ThirdwebProvider, useContract } from "@thirdweb-dev/react";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import Header from '@/components/Header';
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <ThirdwebProvider 
          activeChain="mumbai" 
          clientId="YOUR_CLIENT_ID" // You can get a client id from dashboard settings
          >
          <Header />
          {children}
          </ThirdwebProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
